app/models.py
from . import db,login_manager
from datetime import datetime
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique=True,index=True)
    pass_secure = db.Column(db.String(255))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    # relationships
    
   

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self,password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User {self.username}'

app/main/forms.py
from flask_wtf import FlaskForm 
from wtforms import SelectField,StringField,SubmitField,TextAreaField,PasswordField,BooleanField
from wtforms.validators import Required,Email,EqualTo
from wtforms import ValidationError

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
from flask_uploads import UploadSet, configure_uploads, IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()
simple = SimpleMDE()


def create_app(config_name):

    app = Flask(__name__)

    #Creating application configurations
    app.config.from_object(config_options[config_name])
    config_options[config_name].init_app(app)

    #Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)


    #configure UploadSet
    configure_uploads(app,photos)

    from . auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix='/authentication')

    #Registering the blueprint
    from . main import main as main_blueprint
    app.register_blueprint(main_blueprint)


    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from os import uname
from flask import render_template
from flask.wrappers import Request
from . import main
from flask_login import login_required,current_user
from flask import render_template,request,redirect,url_for,abort
from ..models import User
from .forms import UpdateProfile
from .. import db,photos
import requests
from ..utils import Util,Climate
from pprint import pprint
import urllib.request,json
from config import Config

@main.route('/',methods=['GET','POST'])
def index():
    '''
    View root page function that returns the index page and its data.
    '''
    title = 'WeatherForecast'


    return render_template('index.html', title = title)




@main.route('/search',methods=['GET','POST'])
@login_required
def search():
    '''
    View root page function that returns the index page and its data.
    '''
    title = 'WeatherForecast'
    city = "Nairobi"
    base_url = "https://api.openweathermap.org/data/2.5/weather?appid="+Config.API_Key+"&q=" + city
    weather_data = requests.get(base_url).json()
    pprint(Util.parse_weather_data(weather_data))
    data = Util.parse_weather_data(weather_data)

    if city is None:
        abort(404)

    if request.method == 'POST':
        city = request.form.get("place")
        base_url = "https://api.openweathermap.org/data/2.5/weather?appid="+Config.API_Key+"&q=" + city
        weather_data = requests.get(base_url).json()
        pprint(Util.parse_weather_data(weather_data))
        data = Util.parse_weather_data(weather_data)
    return render_template('search.html', title = title, data = data)





# @main.route('/climate',methods=['GET','POST'])
# @login_required
# def climate():
#     '''
#     View root page function that returns the index page and its data.
#     '''
#     title = 'WeatherForecast'

#     city = "Nakuru"

#     base_url = "https://pro.openweathermap.org/data/2.5/forecast/climate?q="+ city +"&appid="+Config.API_Key
#     # base_url = "https://pro.openweathermap.org/data/2.5/forecast/climate?appid="+Config.API_Key+"&q" + city

#     climate_data = requests.get(base_url).json()
#     pprint(Climate.parse_climate_data(climate_data))
#     climate_data = Climate.parse_climate_data(climate_data)
  
#     if request.method == 'POST':

#         city = request.form.get("climate")

       
#         base_url = "https://pro.openweathermap.org/data/2.5/forecast/climate?q="+ city +"&appid="+Config.API_Key
#         # base_url = "https://api.openweathermap.org/data/2.5/forecast/climate?appid="+Config.API_Key+"&q=" + city

#         climate_data = requests.get(base_url).json()

#         pprint(Climate.parse_climate_data(climate_data))
#         climate_data = Climate.parse_climate_data(climate_data)
#     return render_template('climate.html', title = title, climate_data = climate_data)

    


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar block  --> 
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        
        {% if title %}
        <title> {{ title }}</title>
        {% else %}
        <title> Welcome to the best Movie Review website </title>
        {% endif %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    </head>
    <body>
        <!-- Content block -->

        {% block content %}

        {% endblock%}


    </body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</html>

app/templates/climate.html
{% extends 'base.html'%} {% block styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" /> {% endblock %} {% block content %}

<body>
    <form method="post">
        <input type="text" name="climate" placeholder="Search for a City" class="form-control">
        <input type="submit" value="Submit" class="btn btn-default">
    </form>

    <ul>
        <!-- <li>Latitude:{{ climate_data.latitude }}</li>
        <li>Longitude:{{ climate_data.longitude }}</li> -->
        <li>Day:{{ climate_data.day }}</li>
        <li>Minimum temperature:{{ climate_data.min }}</li>
        <li>Maximum temperature:{{ climate_data.max }}</li>
        <li>Night:{{ climate_data.night }}</li>
        <li>Evening:{{ climate_data.eve }}</li>
        <li>Morning:{{ climate_data.morn }}</li>


    </ul>
</body>
{% endblock%}

app/templates/index.html
{% extends 'base.html'%}  
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='js/particles.js')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='js/app.js')}}">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bowlby+One+SC&family=Shippori+Antique&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
{% endblock %}

{% block content%}
<body>
  <style>
    #particles-js{
    background-image: url(static/images/dull.jpeg);
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    height: 110vh;
    overflow: hidden;
    width: 100%;

    
}
  </style>
  <div id="particles-js">
    <div class="text-center container-full" style="color: white;font-weight: bold;">
      <div class="integrity">
        <h2 class="display-2 head">Weather Forecast</h2>
        <div class="submit"><div class="btns"><a href="{{url_for('auth.register')}}">Sign up</a></div></div>
      </div>
    </div>
    <footer class="footer">
        <!-- Facebook -->
        <i class="fab fa-facebook-f"></i>

        <!-- Twitter -->
        <i class="fab fa-twitter"></i>

        <!-- Instagram -->
        <i class="fab fa-instagram"></i>
        <!-- Youtube -->
        <i class="fab fa-youtube"></i>

        <!-- Slack -->
        <i class="fab fa-slack-hash"></i>
    </footer>
  </div>
<script src="static/js/particles.js"></script>
<script src="static/js/app.js"></script>
    
</body>


{% endblock%}

app/templates/navbar.html
<div class="navbar navbar-expand-lg bg-dark navbar-fixed-top navigation">
    <div class="container-fluid navigate">
        <div class="navbar-header text-white">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> Home </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="navbar-nav navbar-brand brenda">
                <li><a href="/search">Search</a></li>
            </ul>
            
            <ul class="navbar-nav navbar-right navbar-brand brenda">
                {% if current_user.is_authenticated %}
                <li class="user"><a href="{{url_for('main.profile',uname=current_user.username)}}"><i class="fa fa-user" aria-hidden="true"></i>   {{current_user.username}}</a></li>
                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                {% else %}
                <li class="nav-link"><a href="{{url_for('auth.login')}}">Sign in</a></li>
                {%endif%}
            </ul>
        </div>
    </div>
  </div>
  
</div>

app/templates/profile/profile.html
{% extends 'base.html'%}


{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
  integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
{% endblock %}


{% block content %}
<body class="profile">
<div class="container">
    <div class="row">
        <!-- displaying  Username-->
        <div class="col-md-4 prof">
            <h3> {{user.username| capitalize}} </h3>
            <!--Displaying user bio-->
            {% if user.bio %}
            <p> {{user.bio}}</p>
            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            <p>{{user.email}}</p>
            {% endif %}
            {% if user == current_user %}
            <a href="{{url_for('main.update_profile',uname=user.username)}}" class="edit" style="color: #fff;font-size: medium;">Edit profile</a>
            
            {% endif %}
        </div>
        <!--Display profile photo-->
        <div class="col-md-4 prof2">
            {%if user.profile_pic_path%}
            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
            {%else%}
            <p style="font-size: medium;">Profile picture not available</p>
            {%endif%}

            {%if user==current_user%}
            <form action="{{url_for('main.update_pic',uname=user.username)}}" method="POST" enctype="multipart/form-data">
                <input type="file" name="photo" class="form-control" required id=""><br>
                <input type="submit" class="in">
            </form>
            {% endif %}
        </div>
        <div class="col-md-4">
        </div>
    </div>
</div>
</body>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
  integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
{% endblock %}

{% block content %}
<body class="update">
  <div class="container upd">
    <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 date">
    {{wtf.quick_form(form,button_map={'submit':'danger'})}}
  </div>
    <div class="col-md-2"></div>
  </div>
  </div>
</body>
{% endblock %}

app/templates/search.html
{% extends 'base.html'%} {% block styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"> {% endblock %} {% block content %}

<body class="fore">

    <div class="container good">
        <div class="search" style="width: 70%;">
            <form method="post">
                <input type="text" name="place" placeholder="Search for a City" class="form-control">
                <input type="submit" value="Submit" class="btn btn-default joan">
            </form>
        </div>
    </div>

    <div class="container-full text-center ivan">



        <div class="row  space">
            <div class="col-md-4">
                <div class="hum">
                    <p><i class="bi bi-moisture  press"></i>Pressure: <span>{{ data.pressure }}</span></p>
                </div>
                <div class="hum">
                    <p><i class="bi bi-cloud-sun-fill  day"></i>Day: <span>{{ data.temperature }}</span></p>
                </div>
                <div class="hum">
                    <p><i class="bi bi-thermometer-high  high"></i>Maximum temperature: <span>{{ data.temp_max }}</span></p>
                </div>

            </div>
            <div class="col-md-4">
                <div class="hum">
                    <p><i class="bi bi-sunrise-fill rise"></i>Sunrise: <span>{{ data.sunrise }}</span></p>
                </div>

                <div class="hum">
                    <p><i class="bi bi-wind  wind"></i>Windspeed: <span>{{ data.speed }}</span></p>
                </div>
                <div class="hum">
                    <p><i class="bi bi-compass-fill  comp"></i>Latitude: <span>{{ data.latitude }}</span></p>
                </div>
            </div>

            <div class="col-md-4">
                <div class="hum">
                    <p><i class="bi bi-thermometer-low  low"></i>Minimum Temperature: <span>{{ data.temp_min }}</span></p>
                </div>
                <div class="hum">
                    <p><i class="bi bi-cloud-fog-fill  fog"></i>Visibility: <span>{{ data.visibility }}</span></p>
                </div>
                <div class="hum">
                    <p><i class="bi bi-droplet-fill  water"></i><i class="bi bi-droplet-fill  water"></i>Humidity: <span>{{ data.humidity }}</span></p>
                </div>

            </div>
        </div>


    </div>





</body>

{% endblock%}